version: '3.8'

x-logging: &default-logging
  options:
    max-size: '10m'
    max-file: '2'
  driver: local

services:
  api:
    container_name: api
    build:
      context: ./api
      target: development
    logging: *default-logging
    ports:
      - '8080:8080'
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api/:/app:delegated
    working_dir: /app

  web:
    container_name: web
    build:
      context: ./web
      target: development
    logging: *default-logging
    ports:
      - '3000:3000'
    env_file:
      - ./web/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./web/:/app:delegated
    working_dir: /app

  db:
    container_name: lah22_db
    logging: *default-logging
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - db_data:/data/db
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/heja-test --quiet` ] && echo 0 || echo 1'
      interval: 2s
      start_period: 2s
      timeout: 1.5s
      retries: 10

volumes:
  db_data:
