name: Deploy to GHCR
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to GHCR
        env:
          GH_KEY: ${{ secrets.GH_KEY }}
        run: docker login ghcr.io -u kentos -p $GH_KEY
      - name: Build image
        env:
          GH_PACKAGE: ${{ secrets.GH_PACKAGE }}
        run: |
          cd ./api
          docker build --target=production --platform=linux/amd64 -t $GH_PACKAGE .
      - name: Push image
        env:
          GH_PACKAGE: ${{ secrets.GH_PACKAGE }}
        run: docker push $GH_PACKAGE
